title: "control::flow"
email: shvedov89@gmail.com
description: >
  control::flow — a personal blog about C# programming language, IDE tooling, compilers and .NET runtime
baseurl: ""
url: "http://controlflow.github.io"

giscus:
  repo: "controlflow/controlflow.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnkzMzA5NDY4NA=="
  category: "Announcements"
  category_id: "DIC_kwDOAfj8HM4DF6ph"

lsi: false
safe: true
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - serve.cmd
  - serve.ps1
  - vendor
