title: "control::flow"
email: shvedov89@gmail.com
description: >
  control::flow — персональный блог о языках программирования C# и F#,
  IDE-инструментах и компиляторах, среде исполнения CLR и системах типов
baseurl: ""
url: "http://controlflow.github.io"

markdown: kramdown