# Site settings
title: "control::flow"
email: shvedov89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  control::flow — персональный блог о языках программирования C# и F#,
  IDE-инструментах и компиляторах, среде исполнения CLR и системах типов.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://controlflow.github.io"

# Build settings
# markdown: kramdown
markdown: redcarpet

redcarpet:
  extensions: ["strikethrough"]